application: stephanielearnstocode
version: 2
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /assets/stylesheets
  static_dir: assets/stylesheets

- url: /.*
  script: main.app

